version: '3.8'

services:
  vite-frontend:
    build: ./frontend
    ports:
      - "${VITE_PORT:-3000}:3000"
    depends_on:
      - express-api
    environment:
      API_URL: "http://localhost:${NODE_PORT:-3000}"

  express-api:
    build: ./api
    ports:
      - "${NODE_PORT:-3000}:${NODE_PORT:-3000}"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_NAME}"

  db:
    image: postgres:16.2-alpine3.18
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_NAME}"
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      PGPORT: "${POSTGRES_PORT:-5432}"
